### ISSUE TITLE
Plot Biblioreference

### ISSUE THREAD

**Issue by florianjansen** [fmsabatini/sPlotOpen_Code#3]
"Data from Turobevg come with a dictionary of references. These references, however, are not formally formatted, but are simple strings of text. For the time being, we keep them like that.
It would be more efficient to store the data using a dictionary style, where Biblioreferences are referred to with a symbol or short string, and reported in full in an associate reference list."

For vegetweb.de we use a self-constructed bibliographic reference software for that. The workflow is the following:
1. Enter the bibliographic source in https://quarasek.infinitenature.org/quarasek
1. Give it a unique Turboveg REFERENC id (on sheet Attribute)
1. Enter the id for all respective plots in Turboveg
1. Information from Quarasek can be accessed with API

You are invited to think about possibilities to integrate this workflow into new sPlot versions.

**Comment by fmsabatini** [comment]
I didn't know about that! Let's discuss about it in the next SC
